Something went wrong with: https://www.zillow.com/homedetails/Schiller-Park-IL-60176/2077837605_zpid/Traceback (most recent call last):
  File "/Users/jarora/PycharmProjects/websiteScarper/zillow/zillow_scarper.py", line 49, in <module>
    zillow.zillow_functions.record(property_link,save_xml=False)
  File "/Users/jarora/PycharmProjects/websiteScarper/zillow/zillow_functions.py", line 234, in record
    dom = record_xml_util(property_page_soup)
  File "/Users/jarora/PycharmProjects/websiteScarper/zillow/zillow_functions.py", line 221, in record_xml_util
    record_xml['other_details'] = get_other_details(property_page_soup)
  File "/Users/jarora/PycharmProjects/websiteScarper/zillow/zillow_functions.py", line 194, in get_other_details
    bold_heading_groups = details_soup.find_all('div', recursive=False)[0].find_all('div', recursive=False)
IndexError: list index out of range
